source 'https://rubygems.org'
gem 'sinatra', '>= 1.0'
gem 'rake'
gem 'data_mapper'
gem 'dm-core'
gem 'dm-sqlite-adapter'
gem 'dm-timestamps'
gem 'dm-validations'
gem 'dm-aggregates'
gem 'dm-migrations'
gem 'haml'
gem 'sinatra-cross_origin', '~> 0.3.1'
gem 'pry'
gem 'wolfram-alpha'
gem 'activesupport'
